# Generated by Django 5.2.4 on 2025-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_ticket_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('offer', 'پیشنهاد'), ('criticism', 'انتقاد'), ('report', 'گزارش')], default='offer', max_length=250),
        ),
    ]
