# Generated by Django 5.2.4 on 2025-12-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_user_following_cantact_user_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cantact',
            new_name='Contact',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='social_cont_created_371f37_idx',
            old_name='social_cant_created_ad8e90_idx',
        ),
    ]
