# Generated by Django 5.2.4 on 2025-12-24 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_rename_cantact_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='social.Contact', through_fields=('user_from', 'user_to'), to=settings.AUTH_USER_MODEL),
        ),
    ]
