# Generated by Django 5.2.4 on 2025-12-24 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='social.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
