# Generated by Django 5.2.4 on 2025-12-24 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', through='social.Contact', through_fields=('user_from', 'user_to'), to=settings.AUTH_USER_MODEL),
        ),
    ]
