# Generated by Django 5.2.4 on 2025-12-25 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_remove_user_following_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='social.Contact', through_fields=('user_to', 'user_from'), to=settings.AUTH_USER_MODEL),
        ),
    ]
