# Generated by Django 5.2.4 on 2025-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_remove_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='مدرس', max_length=250, null=True, verbose_name='شغل'),
        ),
    ]
