# Generated by Django 5.2.4 on 2026-01-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_alter_user_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view', 'can access other personal page')]},
        ),
    ]
