# Generated by Django 5.2.4 on 2026-01-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
